/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zw_android_flutter_activity_demo_ProfilerActivity */

#ifndef _Included_com_zw_android_flutter_activity_demo_ProfilerActivity
#define _Included_com_zw_android_flutter_activity_demo_ProfilerActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zw_android_flutter_activity_demo_ProfilerActivity
 * Method:    test_leak
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zw_android_1flutter_activity_demo_ProfilerActivity_test_1leak
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
