/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zw_android_flutter_activity_demo_CPPActivity */

#ifndef _Included_com_zw_android_flutter_activity_demo_CPPActivity
#define _Included_com_zw_android_flutter_activity_demo_CPPActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zw_android_flutter_activity_demo_CPPActivity
 * Method:    lock
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zw_android_1flutter_activity_demo_CPPActivity_lock
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
