/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zw_android_flutter_JNITest */

#ifndef _Included_com_zw_android_flutter_JNITest
#define _Included_com_zw_android_flutter_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zw_android_flutter_JNITest
 * Method:    test1
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_zw_android_1flutter_JNITest_test1
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
