/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zw_android_flutter_activity_demo_NativeActivity */

#ifndef _Included_com_zw_android_flutter_activity_demo_NativeActivity
#define _Included_com_zw_android_flutter_activity_demo_NativeActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zw_android_flutter_activity_demo_NativeActivity
 * Method:    native_test1
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zw_android_1flutter_activity_demo_NativeActivity_native_1test1
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
