/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zw_android_flutter_activity_demo_STLActivity */

#ifndef _Included_com_zw_android_flutter_activity_demo_STLActivity
#define _Included_com_zw_android_flutter_activity_demo_STLActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zw_android_flutter_activity_demo_STLActivity
 * Method:    test_btn_vector_list
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zw_android_1flutter_activity_demo_STLActivity_test_1btn_1vector_1list
  (JNIEnv *, jclass);

/*
 * Class:     com_zw_android_flutter_activity_demo_STLActivity
 * Method:    test_map
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zw_android_1flutter_activity_demo_STLActivity_test_1map
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
