/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zw_app2_NativeTest1 */

#ifndef _Included_com_zw_app2_NativeTest1
#define _Included_com_zw_app2_NativeTest1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zw_app2_NativeTest1
 * Method:    test1
 * Signature: ()V
 */
JNIEXPORT void JNICALL
Java_com_zw_app2_NativeTest1_test1
        (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
