platform :ios, '10.0'

flutter_application_path = '../flutter_module/'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'ios-flutter' do

  use_frameworks!

  install_all_flutter_pods(flutter_application_path)

end